//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RouteOptimization
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public decimal order_id { get; set; }
        public Nullable<decimal> store_id { get; set; }
        public Nullable<decimal> channel_id { get; set; }
        public Nullable<decimal> payment_order_id { get; set; }
        public Nullable<decimal> delivery_order_id { get; set; }
        public string order_status { get; set; }
        public Nullable<double> order_amount { get; set; }
        public string order_delivery_fee { get; set; }
        public string order_delivery_cost { get; set; }
        public string order_created_hour { get; set; }
        public string order_created_minute { get; set; }
        public string order_created_day { get; set; }
        public string order_created_month { get; set; }
        public Nullable<int> order_created_year { get; set; }
        public string order_moment_created { get; set; }
        public string order_moment_accepted { get; set; }
        public string order_moment_ready { get; set; }
        public string order_moment_collected { get; set; }
        public string order_moment_in_expedition { get; set; }
        public string order_moment_delivering { get; set; }
        public string order_moment_delivered { get; set; }
        public string order_moment_finished { get; set; }
        public string order_metric_collected_time { get; set; }
        public string order_metric_paused_time { get; set; }
        public string order_metric_production_time { get; set; }
        public string order_metric_walking_time { get; set; }
        public string order_metric_expediton_speed_time { get; set; }
        public string order_metric_transit_time { get; set; }
        public string order_metric_cycle_time { get; set; }
    }
}
